[project]
name = "free-genai-bootcamp-2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "diagrams>=0.24.1",
    "graphviz>=0.20.3",
]
